/*  Terraduino: Simple automation controller for homestead resource and environmental systems.
    Copyright (C) 2026 NachtRaveVL
    Terraduino Strings
*/

#ifndef TerraStrings_H
#define TerraStrings_H

#include "Terraduino.h"

// Strings Enumeration Table
enum Terra_String : uint16_t {
    TStr_ColonSpace,                            // ": "
    TStr_DoubleSpace,                           // "  "
    TStr_csv,                                   // "csv"
    TStr_dat,                                   // "dat"
    TStr_Disabled,                              // "Disabled"
    TStr_raw,                                   // "raw"
    TStr_txt,                                   // "txt"
    TStr_Undefined,                             // "Undefined"
    TStr_null,                                  // "null"

    TStr_Default_SystemName,                    // "Terraduino"
    TStr_Default_ConfigFilename,                // "Terraduino.cfg"

    TStr_Err_AllocationFailure,                 // "Allocation failure"
    TStr_Err_AlreadyInitialized,                // "Already initialized"
    TStr_Err_AssertionFailure,                  // "Assertion failure"
    TStr_Err_ExportFailure,                     // "Export failure"
    TStr_Err_ImportFailure,                     // "Import failure"
    TStr_Err_InitializationFailure,             // "Initialization failure"
    TStr_Err_InvalidParameter,                  // "Invalid parameter"
    TStr_Err_InvalidPinOrType,                  // "Invalid pin or type"
    TStr_Err_MeasurementFailure,                // "Measurement failure"
    TStr_Err_MissingLinkage,                    // "Missing linkage"
    TStr_Err_NoPositionsAvailable,              // "No positions available"
    TStr_Err_NotConfiguredProperly,             // "Not configured properly"
    TStr_Err_NotYetInitialized,                 // "Not yet initialized"
    TStr_Err_OperationFailure,                  // "Operation failure"
    TStr_Err_UnsupportedOperation,              // "Unsupported operation"

    TStr_Log_RTCBatteryFailure,                 // "RTC battery failure"
    TStr_Log_SystemDataSaved,                   // "System data saved"
    TStr_Log_SystemUptime,                      // "System uptime"
    TStr_Log_CalculatedPumping,                 // " pumping request:"
    TStr_Log_MeasuredPumping,                   // " pumping result:"
    TStr_Log_HasDisabled,                       // " has disabled"
    TStr_Log_HasEnabled,                        // " has enabled"

    TStr_Log_Prefix_Info,                       // "[INFO] "
    TStr_Log_Prefix_Warning,                    // "[WARN] "
    TStr_Log_Prefix_Error,                      // "[ERROR] "

    TStr_Log_Field_Destination_Reservoir,       // "  To reservoir: "
    TStr_Log_Field_Source_Reservoir,            // "  From reservoir: "
    TStr_Log_Field_Time_Calculated,             // "  Pump run time: "
    TStr_Log_Field_Time_Measured,               // "  Elapsed time: "
    TStr_Log_Field_Vol_Calculated,              // "  Est. pumped vol.: "
    TStr_Log_Field_Vol_Measured,                // "  Act. pumped vol.: "

    TStr_Key_ActiveLow,                         // "activeLow"
    TStr_Key_AirTemperatureSensor,              // "airTemperatureSensor"
    TStr_Key_AlwaysFilled,                      // "alwaysFilled"
    TStr_Key_AreaSquareMeters,                  // "areaSquareMeters"
    TStr_Key_AutosaveEnabled,                   // "autosaveEnabled"
    TStr_Key_AutosaveFallback,                  // "autosaveFallback"
    TStr_Key_AutosaveInterval,                  // "autosaveInterval"
    TStr_Key_BitRes,                            // "bitRes"
    TStr_Key_CalibrationUnits,                  // "calibrationUnits"
    TStr_Key_Channel,                           // "channel"
    TStr_Key_Circulator,                        // "circulator"
    TStr_Key_CollectionEfficiency,              // "collectionEfficiency"
    TStr_Key_ContinuousFlowRate,                // "continuousFlowRate"
    TStr_Key_ContinuousPowerUsage,              // "continuousPowerUsage"
    TStr_Key_CtrlInMode,                        // "ctrlInMode"
    TStr_Key_DataFilePrefix,                    // "dataFilePrefix"
    TStr_Key_Destination,                       // "destination"
    TStr_Key_DestinationStartPercent,           // "destinationStartPercent"
    TStr_Key_DestinationStopPercent,            // "destinationStopPercent"
    TStr_Key_DetriggerDelay,                    // "detriggerDelay"
    TStr_Key_DetriggerTol,                      // "detriggerTol"
    TStr_Key_DispOutMode,                       // "dispOutMode"
    TStr_Key_EmptyTrigger,                      // "emptyTrigger"
    TStr_Key_EnableMode,                        // "enableMode"
    TStr_Key_FilledTrigger,                     // "filledTrigger"
    TStr_Key_FlowRateSensor,                    // "flowRateSensor"
    TStr_Key_FlowRateUnits,                     // "flowRateUnits"
    TStr_Key_FlowSensor,                        // "flowSensor"
    TStr_Key_HighTrigger,                       // "highTrigger"
    TStr_Key_HumiditySensor,                    // "humiditySensor"
    TStr_Key_Id,                                // "id"
    TStr_Key_InputPin,                          // "inputPin"
    TStr_Key_LevelSensor,                       // "levelSensor"
    TStr_Key_LimitTrigger,                      // "limitTrigger"
    TStr_Key_Location,                          // "location"
    TStr_Key_LogFilePrefix,                     // "logFilePrefix"
    TStr_Key_LogLevel,                          // "logLevel"
    TStr_Key_Logger,                            // "logger"
    TStr_Key_LogToSDCard,                       // "logToSDCard"
    TStr_Key_LogToWiFiStorage,                  // "logToWiFiStorage"
    TStr_Key_LowTrigger,                        // "lowTrigger"
    TStr_Key_MACAddress,                        // "macAddress"
    TStr_Key_MaxActiveAtOnce,                   // "maxActiveAtOnce"
    TStr_Key_MaxContinuousMs,                   // "maxContinuousMs"
    TStr_Key_MaximumFlowLpm,                    // "maximumFlowLpm"
    TStr_Key_MaxPower,                          // "maxPower"
    TStr_Key_MaxStoreTempC,                     // "maxStoreTempC"
    TStr_Key_MaxTemperature,                    // "maxTemperature"
    TStr_Key_MaxVolume,                         // "maxVolume"
    TStr_Key_MeasurementRow,                    // "measurementRow"
    TStr_Key_MeasurementUnits,                  // "measurementUnits"
    TStr_Key_MeasureMode,                       // "measureMode"
    TStr_Key_MinimumFlowLpm,                    // "minimumFlowLpm"
    TStr_Key_Mode,                              // "mode"
    TStr_Key_Multiplier,                        // "multiplier"
    TStr_Key_OffDifferentialC,                  // "offDifferentialC"
    TStr_Key_Offset,                            // "offset"
    TStr_Key_OnDifferentialC,                   // "onDifferentialC"
    TStr_Key_OutputPin,                         // "outputPin"
    TStr_Key_OutputReservoir,                   // "outputReservoir"
    TStr_Key_Pin,                               // "pin"
    TStr_Key_PollingInterval,                   // "pollingInterval"
    TStr_Key_PowerUsageSensor,                  // "powerUsageSensor"
    TStr_Key_PowerUnits,                        // "powerUnits"
    TStr_Key_PressureSensor,                    // "pressureSensor"
    TStr_Key_PublishToSDCard,                   // "pubToSDCard"
    TStr_Key_PublishToWiFiStorage,              // "pubToWiFiStorage"
    TStr_Key_Publisher,                         // "publisher"
    TStr_Key_PWMChannel,                        // "pwmChannel"
    TStr_Key_PWMFrequency,                      // "pwmFrequency"
    TStr_Key_Pump,                              // "pump"
    TStr_Key_RailName,                          // "railName"
    TStr_Key_RainfallSensor,                    // "rainfallSensor"
    TStr_Key_RainRateSensor,                    // "rainRateSensor"
    TStr_Key_ReportedType,                      // "reportedType"
    TStr_Key_ReservoirName,                     // "reservoirName"
    TStr_Key_Revision,                          // "revision"
    TStr_Key_Scheduler,                         // "scheduler"
    TStr_Key_SensorName,                        // "sensorName"
    TStr_Key_SolarRadiationSensor,              // "solarRadiationSensor"
    TStr_Key_Source,                            // "source"
    TStr_Key_SourceTemperatureSensor,           // "sourceTemperatureSensor"
    TStr_Key_StaleAfterMs,                      // "staleAfterMs"
    TStr_Key_Store,                             // "store"
    TStr_Key_SumpAlarmPercent,                  // "sumpAlarmPercent"
    TStr_Key_SumpStartPercent,                  // "sumpStartPercent"
    TStr_Key_SumpStopPercent,                   // "sumpStopPercent"
    TStr_Key_SystemMode,                        // "systemMode"
    TStr_Key_SystemName,                        // "systemName"
    TStr_Key_TemperatureSensor,                 // "temperatureSensor"
    TStr_Key_TemperatureUnits,                  // "temperatureUnits"
    TStr_Key_TimeZoneOffset,                    // "timeZoneOffset"
    TStr_Key_Timestamp,                         // "timestamp"
    TStr_Key_Tolerance,                         // "tolerance"
    TStr_Key_ToleranceHigh,                     // "toleranceHigh"
    TStr_Key_ToleranceLow,                      // "toleranceLow"
    TStr_Key_TriggerBelow,                      // "triggerBelow"
    TStr_Key_TriggerOutside,                    // "triggerOutside"
    TStr_Key_Type,                              // "type"
    TStr_Key_Units,                             // "units"
    TStr_Key_Value,                             // "value"
    TStr_Key_Version,                           // "version"
    TStr_Key_VolumeSensor,                      // "volumeSensor"
    TStr_Key_VolumeUnits,                       // "volumeUnits"
    TStr_Key_WaterTemperatureSensor,            // "waterTemperatureSensor"
    TStr_Key_WiFiPassword,                      // "wifiPassword"
    TStr_Key_WiFiPasswordSeed,                  // "wifiPasswordSeed"
    TStr_Key_WiFiSSID,                          // "wifiSSID"
    TStr_Key_WindDirectionSensor,               // "windDirectionSensor"
    TStr_Key_WindSpeedSensor,                   // "windSpeedSensor"

    TStr_Enum_AC110V,                           // "AC110V"
    TStr_Enum_AC220V,                           // "AC220V"
    TStr_Enum_Active,                           // "Active"
    TStr_Enum_Analog,                           // "Analog"
    TStr_Enum_AnalogInput,                      // "AnalogInput"
    TStr_Enum_AnalogJoystick,                   // "AnalogJoystick"
    TStr_Enum_AnalogOutput,                     // "AnalogOutput"
    TStr_Enum_Angle,                            // "Angle"
    TStr_Enum_AscOrder,                         // "AscOrder"
    TStr_Enum_Automatic,                        // "Automatic"
    TStr_Enum_Average,                          // "Average"
    TStr_Enum_Binary,                           // "Binary"
    TStr_Enum_Circulator,                       // "Circulator"
    TStr_Enum_Complete,                         // "Complete"
    TStr_Enum_Count,                            // "Count"
    TStr_Enum_Current,                          // "Current"
    TStr_Enum_Custom,                           // "Custom"
    TStr_Enum_CustomOLED,                       // "CustomOLED"
    TStr_Enum_DC12V,                            // "DC12V"
    TStr_Enum_DC24V,                            // "DC24V"
    TStr_Enum_DC3V3,                            // "DC3V3"
    TStr_Enum_DC48V,                            // "DC48V"
    TStr_Enum_DC5V,                             // "DC5V"
    TStr_Enum_DescOrder,                        // "DescOrder"
    TStr_Enum_Digital,                          // "Digital"
    TStr_Enum_DigitalInput,                     // "DigitalInput"
    TStr_Enum_DigitalInputPullDown,             // "DigitalInputPullDown"
    TStr_Enum_DigitalInputPullUp,               // "DigitalInputPullUp"
    TStr_Enum_DigitalOutput,                    // "DigitalOutput"
    TStr_Enum_DigitalOutputPushPull,            // "DigitalOutputPushPull"
    TStr_Enum_Display,                          // "Display"
    TStr_Enum_Distance,                         // "Distance"
    TStr_Enum_Diverter,                         // "Diverter"
    TStr_Enum_Energy,                           // "Energy"
    TStr_Enum_Equal,                            // "Equal"
    TStr_Enum_Fan,                              // "Fan"
    TStr_Enum_Fault,                            // "Fault"
    TStr_Enum_Flow,                             // "Flow"
    TStr_Enum_FlowSensor,                       // "FlowSensor"
    TStr_Enum_GreaterOrEqual,                   // "GreaterOrEqual"
    TStr_Enum_GreaterThan,                      // "GreaterThan"
    TStr_Enum_Heater,                           // "Heater"
    TStr_Enum_High,                             // "High"
    TStr_Enum_Highest,                          // "Highest"
    TStr_Enum_Humidity,                         // "Humidity"
    TStr_Enum_HumiditySensor,                   // "HumiditySensor"
    TStr_Enum_Idle,                             // "Idle"
    TStr_Enum_IL3820,                           // "IL3820"
    TStr_Enum_IL3820V2,                         // "IL3820V2"
    TStr_Enum_ILI9341,                          // "ILI9341"
    TStr_Enum_Imperial,                         // "Imperial"
    TStr_Enum_Inactive,                         // "Inactive"
    TStr_Enum_InOrder,                          // "InOrder"
    TStr_Enum_IOExpander,                       // "IOExpander"
    TStr_Enum_Irradiance,                       // "Irradiance"
    TStr_Enum_LCD16x2,                          // "LCD16x2"
    TStr_Enum_LCD20x4,                          // "LCD20x4"
    TStr_Enum_Leak,                             // "Leak"
    TStr_Enum_LeakSensor,                       // "LeakSensor"
    TStr_Enum_LessOrEqual,                      // "LessOrEqual"
    TStr_Enum_LessThan,                         // "LessThan"
    TStr_Enum_Level,                            // "Level"
    TStr_Enum_LevelSensor,                      // "LevelSensor"
    TStr_Enum_LiquidFlowRate,                   // "LiquidFlowRate"
    TStr_Enum_LiquidVolume,                     // "LiquidVolume"
    TStr_Enum_Low,                              // "Low"
    TStr_Enum_Lowest,                           // "Lowest"
    TStr_Enum_Manual,                           // "Manual"
    TStr_Enum_Matrix2x2,                        // "Matrix2x2"
    TStr_Enum_Matrix3x4,                        // "Matrix3x4"
    TStr_Enum_Matrix4x4,                        // "Matrix4x4"
    TStr_Enum_Metric,                           // "Metric"
    TStr_Enum_Multiply,                         // "Multiply"
    TStr_Enum_Municipal,                        // "Municipal"
    TStr_Enum_Network,                          // "Network"
    TStr_Enum_Normal,                           // "Normal"
    TStr_Enum_NotEqual,                         // "NotEqual"
    TStr_Enum_Percentile,                       // "Percentile"
    TStr_Enum_Power,                            // "Power"
    TStr_Enum_Pressure,                         // "Pressure"
    TStr_Enum_PressureSensor,                   // "PressureSensor"
    TStr_Enum_Pump,                             // "Pump"
    TStr_Enum_Radio,                            // "Radio"
    TStr_Enum_Rainfall,                         // "Rainfall"
    TStr_Enum_RainfallSensor,                   // "RainfallSensor"
    TStr_Enum_RainRate,                         // "RainRate"
    TStr_Enum_Rainwater,                        // "Rainwater"
    TStr_Enum_Raw,                              // "Raw"
    TStr_Enum_Reclaimed,                        // "Reclaimed"
    TStr_Enum_Remote,                           // "Remote"
    TStr_Enum_RemoteControl,                    // "RemoteControl"
    TStr_Enum_Requested,                        // "Requested"
    TStr_Enum_Reserve,                          // "Reserve"
    TStr_Enum_ResistiveTouch,                   // "ResistiveTouch"
    TStr_Enum_RevOrder,                         // "RevOrder"
    TStr_Enum_RotaryEncoder,                    // "RotaryEncoder"
    TStr_Enum_RTC,                              // "RTC"
    TStr_Enum_Scientific,                       // "Scientific"
    TStr_Enum_SH1106,                           // "SH1106"
    TStr_Enum_SolarRadiation,                   // "SolarRadiation"
    TStr_Enum_SolarRadiationSensor,             // "SolarRadiationSensor"
    TStr_Enum_Speed,                            // "Speed"
    TStr_Enum_SSD1305,                          // "SSD1305"
    TStr_Enum_SSD1305x32Ada,                    // "SSD1305x32Ada"
    TStr_Enum_SSD1305x64Ada,                    // "SSD1305x64Ada"
    TStr_Enum_SSD1306,                          // "SSD1306"
    TStr_Enum_SSD1607,                          // "SSD1607"
    TStr_Enum_ST7735,                           // "ST7735"
    TStr_Enum_ST7789,                           // "ST7789"
    TStr_Enum_Storage,                          // "Storage"
    TStr_Enum_Stored,                           // "Stored"
    TStr_Enum_SumpPump,                         // "SumpPump"
    TStr_Enum_Surface,                          // "Surface"
    TStr_Enum_Tank,                             // "Tank"
    TStr_Enum_Temperature,                      // "Temperature"
    TStr_Enum_TemperatureSensor,                // "TemperatureSensor"
    TStr_Enum_TFTTouch,                         // "TFTTouch"
    TStr_Enum_Thermal,                          // "Thermal"
    TStr_Enum_ThermalReservoir,                 // "ThermalReservoir"
    TStr_Enum_TouchScreen,                      // "TouchScreen"
    TStr_Enum_Unknown,                          // "Unknown"
    TStr_Enum_UpDownButtons,                    // "UpDownButtons"
    TStr_Enum_UpDownESP32Touch,                 // "UpDownESP32Touch"
    TStr_Enum_Valve,                            // "Valve"
    TStr_Enum_Variable,                         // "Variable"
    TStr_Enum_Voltage,                          // "Voltage"
    TStr_Enum_Water,                            // "Water"
    TStr_Enum_WaterReservoir,                   // "WaterReservoir"
    TStr_Enum_Well,                             // "Well"
    TStr_Enum_WindDirection,                    // "WindDirection"
    TStr_Enum_WindDirectionSensor,              // "WindDirectionSensor"
    TStr_Enum_WindSpeed,                        // "WindSpeed"
    TStr_Enum_WindSpeedSensor,                  // "WindSpeedSensor"

    TStr_Unit_Degree,                           // "deg"
    TStr_Unit_Feet,                             // "ft"
    TStr_Unit_Gallons,                          // "gal"
    TStr_Unit_Hectopascals,                     // "hPa"
    TStr_Unit_Inches,                           // "in"
    TStr_Unit_KilometersPerHour,                // "km/h"
    TStr_Unit_Kilopascals,                      // "kPa"
    TStr_Unit_KilowattHours,                    // "kWh"
    TStr_Unit_MilesPerHour,                     // "mph"
    TStr_Unit_Millimeters,                      // "mm"
    TStr_Unit_Minutes,                          // "min"
    TStr_Unit_PerHour,                          // "/h"
    TStr_Unit_PerMinute,                        // "/min"
    TStr_Unit_PerSecond,                        // "/s"
    TStr_Unit_PoundsPerSquareInch,              // "psi"
    TStr_Unit_Radians,                          // "rad"
    TStr_Unit_WattsPerSquareMeter,              // "W/m2"

    TStr_Count
};

extern const char *TStr_Blank;

typedef bool (*StringProvider)(void *context, Terra_String stringId, String *valueOut);
void setStringProvider(StringProvider provider, void *context = nullptr);
String stringFromPGM(Terra_String strNum);
String stringFromPGMAddr(const char *flashStr);
#define SFP(strNum) stringFromPGM((strNum))

#ifndef TERRA_DISABLE_BUILTIN_DATA
const char *pgmAddrForStr(Terra_String strNum);
#define CFP(strNum) pgmAddrForStr((strNum))
#else
#define CFP(strNum) SFP(strNum).c_str()
#endif

bool terraStringIdEqualsIgnoreCase(const String &value, Terra_String stringId);

#endif // /ifndef TerraStrings_H
